algoritmo "semnome"
// Função :
// Autor :
// Data : 08/06/2016
// Seção de Declarações 
var
     nota1, nota2, media: real
inicio
     escreva ("Digite a primeira nota:")
     leia (nota1)
     Escreva ("Digite a segunda nota:")
     leia (nota2)
     
// Calcular a media
media <- (nota1 + nota2)/2
escreval ("Sua média é: ", media)

se media >= 7 entao

escreval ("Aprovado")

senao
    escreval ("Reprovado")

fimse
fimalgoritmo
